Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings("ignore")

print("Libraries imported successfully!")

Libraries imported successfully!

Define Dataset Path

In [2]:
DATA_PATH = "../data/raw/"

print("Dataset path:", DATA_PATH)
print("Path exists:", os.path.exists(DATA_PATH))

Dataset path: ../data/raw/
Path exists: True

Check Available Files

In [3]:
files = os.listdir(DATA_PATH)

print("Files found:")
for file in files:
    print("-", file)

Files found:
- olist_customers_dataset.csv
- olist_geolocation_dataset.csv
- olist_orders_dataset.csv
- olist_order_items_dataset.csv
- olist_order_payments_dataset.csv
- olist_order_reviews_dataset.csv
- olist_products_dataset.csv
- olist_sellers_dataset.csv
- product_category_name_translation.csv

Define File Paths
(Instead of repeatedly writing long paths, define them once.)

In [4]:
CUSTOMERS_FILE = DATA_PATH + "olist_customers_dataset.csv"
GEOLOCATION_FILE = DATA_PATH + "olist_geolocation_dataset.csv"
ORDER_ITEMS_FILE = DATA_PATH + "olist_order_items_dataset.csv"
PAYMENTS_FILE = DATA_PATH + "olist_order_payments_dataset.csv"
REVIEWS_FILE = DATA_PATH + "olist_order_reviews_dataset.csv"
ORDERS_FILE = DATA_PATH + "olist_orders_dataset.csv"
PRODUCTS_FILE = DATA_PATH + "olist_products_dataset.csv"
SELLERS_FILE = DATA_PATH + "olist_sellers_dataset.csv"
TRANSLATION_FILE = DATA_PATH + "product_category_name_translation.csv"

Load All Datasets

In [5]:
customers = pd.read_csv(CUSTOMERS_FILE)
geolocation = pd.read_csv(GEOLOCATION_FILE)
order_items = pd.read_csv(ORDER_ITEMS_FILE)
payments = pd.read_csv(PAYMENTS_FILE)
reviews = pd.read_csv(REVIEWS_FILE)
orders = pd.read_csv(ORDERS_FILE)
products = pd.read_csv(PRODUCTS_FILE)
sellers = pd.read_csv(SELLERS_FILE)
translation = pd.read_csv(TRANSLATION_FILE)

print("All datasets loaded successfully!")

All datasets loaded successfully!

Create Dataset Dictionary

In [6]:
datasets = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "translation": translation
}

print(f"Total datasets loaded: {len(datasets)}")

Total datasets loaded: 9

Dataset Overview

In [7]:
dataset_summary = []

for name, df in datasets.items():
    dataset_summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1]
    })

dataset_summary = pd.DataFrame(dataset_summary)

dataset_summary

       Dataset     Rows  Columns
0    customers    99441        5
1  geolocation  1000163        5
2  order_items   112650        7
3     payments   103886        5
4      reviews    99224        7
5       orders    99441        8
6     products    32951        9
7      sellers     3095        4
8  translation       71        2

Display First 5 Rows

In [8]:
for name, df in datasets.items():
    print("=" * 70)
    print(f"DATASET: {name.upper()}")
    print("=" * 70)
    display(df.head())

======================================================================
DATASET: CUSTOMERS
======================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

======================================================================
DATASET: GEOLOCATION
======================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

======================================================================
DATASET: ORDER_ITEMS
======================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

======================================================================
DATASET: PAYMENTS
======================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

======================================================================
DATASET: REVIEWS
======================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

======================================================================
DATASET: ORDERS
======================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

======================================================================
DATASET: PRODUCTS
======================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

======================================================================
DATASET: SELLERS
======================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

======================================================================
DATASET: TRANSLATION
======================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Check Column Names

In [9]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    for col in df.columns:
        print(col)

======================================================================
CUSTOMERS
======================================================================
customer_id
customer_unique_id
customer_zip_code_prefix
customer_city
customer_state

======================================================================
GEOLOCATION
======================================================================
geolocation_zip_code_prefix
geolocation_lat
geolocation_lng
geolocation_city
geolocation_state

======================================================================
ORDER_ITEMS
======================================================================
order_id
order_item_id
product_id
seller_id
shipping_limit_date
price
freight_value

======================================================================
PAYMENTS
======================================================================
order_id
payment_sequential
payment_type
payment_installments
payment_value

======================================================================
REVIEWS
======================================================================
review_id
order_id
review_score
review_comment_title
review_comment_message
review_creation_date
review_answer_timestamp

======================================================================
ORDERS
======================================================================
order_id
customer_id
order_status
order_purchase_timestamp
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
order_estimated_delivery_date

======================================================================
PRODUCTS
======================================================================
product_id
product_category_name
product_name_lenght
product_description_lenght
product_photos_qty
product_weight_g
product_length_cm
product_height_cm
product_width_cm

======================================================================
SELLERS
======================================================================
seller_id
seller_zip_code_prefix
seller_city
seller_state

======================================================================
TRANSLATION
======================================================================
product_category_name
product_category_name_english

Check Data Types

In [10]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    display(pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str).values
    }))

======================================================================
CUSTOMERS
======================================================================

                     Column Data Type
0               customer_id    object
1        customer_unique_id    object
2  customer_zip_code_prefix     int64
3             customer_city    object
4            customer_state    object

======================================================================
GEOLOCATION
======================================================================

                        Column Data Type
0  geolocation_zip_code_prefix     int64
1              geolocation_lat   float64
2              geolocation_lng   float64
3             geolocation_city    object
4            geolocation_state    object

======================================================================
ORDER_ITEMS
======================================================================

                Column Data Type
0             order_id    object
1        order_item_id     int64
2           product_id    object
3            seller_id    object
4  shipping_limit_date    object
5                price   float64
6        freight_value   float64

======================================================================
PAYMENTS
======================================================================

                 Column Data Type
0              order_id    object
1    payment_sequential     int64
2          payment_type    object
3  payment_installments     int64
4         payment_value   float64

======================================================================
REVIEWS
======================================================================

                    Column Data Type
0                review_id    object
1                 order_id    object
2             review_score     int64
3     review_comment_title    object
4   review_comment_message    object
5     review_creation_date    object
6  review_answer_timestamp    object

======================================================================
ORDERS
======================================================================

                          Column Data Type
0                       order_id    object
1                    customer_id    object
2                   order_status    object
3       order_purchase_timestamp    object
4              order_approved_at    object
5   order_delivered_carrier_date    object
6  order_delivered_customer_date    object
7  order_estimated_delivery_date    object

======================================================================
PRODUCTS
======================================================================

                       Column Data Type
0                  product_id    object
1       product_category_name    object
2         product_name_lenght   float64
3  product_description_lenght   float64
4          product_photos_qty   float64
5            product_weight_g   float64
6           product_length_cm   float64
7           product_height_cm   float64
8            product_width_cm   float64

======================================================================
SELLERS
======================================================================

                   Column Data Type
0               seller_id    object
1  seller_zip_code_prefix     int64
2             seller_city    object
3            seller_state    object

======================================================================
TRANSLATION
======================================================================

                          Column Data Type
0          product_category_name    object
1  product_category_name_english    object

Missing Values

In [11]:
missing_summary = {}

for name, df in datasets.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    
    missing_summary[name] = missing

    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    if len(missing) == 0:
        print("No missing values.")
    else:
        print(missing)

======================================================================
CUSTOMERS
======================================================================
No missing values.

======================================================================
GEOLOCATION
======================================================================
No missing values.

======================================================================
ORDER_ITEMS
======================================================================
No missing values.

======================================================================
PAYMENTS
======================================================================
No missing values.

======================================================================
REVIEWS
======================================================================
review_comment_title      87656
review_comment_message    58247
dtype: int64

======================================================================
ORDERS
======================================================================
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

======================================================================
PRODUCTS
======================================================================
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

======================================================================
SELLERS
======================================================================
No missing values.

======================================================================
TRANSLATION
======================================================================
No missing values.

Missing Value Percentage
 (Counts are useful, but percentages are better for data-quality analysis)

In [12]:
for name, df in datasets.items():
    
    missing_count = df.isnull().sum()
    missing_percentage = (missing_count / len(df)) * 100
    
    missing_table = pd.DataFrame({
        "Missing Count": missing_count,
        "Missing %": missing_percentage.round(2)
    })
    
    missing_table = missing_table[
        missing_table["Missing Count"] > 0
    ]
    
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    if missing_table.empty:
        print("No missing values.")
    else:
        display(missing_table)

======================================================================
CUSTOMERS
======================================================================
No missing values.

======================================================================
GEOLOCATION
======================================================================
No missing values.

======================================================================
ORDER_ITEMS
======================================================================
No missing values.

======================================================================
PAYMENTS
======================================================================
No missing values.

======================================================================
REVIEWS
======================================================================

                        Missing Count  Missing %
review_comment_title            87656      88.34
review_comment_message          58247      58.70

======================================================================
ORDERS
======================================================================

                               Missing Count  Missing %
order_approved_at                        160       0.16
order_delivered_carrier_date            1783       1.79
order_delivered_customer_date           2965       2.98

======================================================================
PRODUCTS
======================================================================

                            Missing Count  Missing %
product_category_name                 610       1.85
product_name_lenght                   610       1.85
product_description_lenght            610       1.85
product_photos_qty                    610       1.85
product_weight_g                        2       0.01
product_length_cm                       2       0.01
product_height_cm                       2       0.01
product_width_cm                        2       0.01

======================================================================
SELLERS
======================================================================
No missing values.

======================================================================
TRANSLATION
======================================================================
No missing values.

Duplicate Records

In [13]:
for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()
    
    print(
        f"{name:<15} → "
        f"{duplicate_count:,} duplicate rows"
    )

customers       → 0 duplicate rows
geolocation     → 261,831 duplicate rows
order_items     → 0 duplicate rows
payments        → 0 duplicate rows
reviews         → 0 duplicate rows
orders          → 0 duplicate rows
products        → 0 duplicate rows
sellers         → 0 duplicate rows
translation     → 0 duplicate rows

Unique Values

In [14]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    unique_values = df.nunique().sort_values()
    
    display(
        unique_values.to_frame("Unique Values")
    )

======================================================================
CUSTOMERS
======================================================================

                          Unique Values
customer_state                       27
customer_city                      4119
customer_zip_code_prefix          14994
customer_unique_id                96096
customer_id                       99441

======================================================================
GEOLOCATION
======================================================================

                             Unique Values
geolocation_state                       27
geolocation_city                      8011
geolocation_zip_code_prefix          19015
geolocation_lat                     717360
geolocation_lng                     717613

======================================================================
ORDER_ITEMS
======================================================================

                     Unique Values
order_item_id                   21
seller_id                     3095
price                         5968
freight_value                 6999
product_id                   32951
shipping_limit_date          93318
order_id                     98666

======================================================================
PAYMENTS
======================================================================

                      Unique Values
payment_type                      5
payment_installments             24
payment_sequential               29
payment_value                 29077
order_id                      99440

======================================================================
REVIEWS
======================================================================

                         Unique Values
review_score                         5
review_creation_date               636
review_comment_title              4527
review_comment_message           36159
review_answer_timestamp          98248
review_id                        98410
order_id                         98673

======================================================================
ORDERS
======================================================================

                               Unique Values
order_status                               8
order_estimated_delivery_date            459
order_delivered_carrier_date           81018
order_approved_at                      90733
order_delivered_customer_date          95664
order_purchase_timestamp               98875
order_id                               99441
customer_id                            99441

======================================================================
PRODUCTS
======================================================================

                            Unique Values
product_photos_qty                     19
product_name_lenght                    66
product_category_name                  73
product_width_cm                       95
product_length_cm                      99
product_height_cm                     102
product_weight_g                     2204
product_description_lenght           2960
product_id                          32951

======================================================================
SELLERS
======================================================================

                        Unique Values
seller_state                       23
seller_city                       611
seller_zip_code_prefix           2246
seller_id                        3095

======================================================================
TRANSLATION
======================================================================

                               Unique Values
product_category_name                     71
product_category_name_english             71

Statistical Summary

In [15]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    display(df.describe().T)

======================================================================
CUSTOMERS
======================================================================

,count,mean,std,min,25%,50%,75%,max
customer_zip_code_prefix,99441.0,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0

======================================================================
GEOLOCATION
======================================================================

,count,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,36574.166466,30549.335710,1001.000000,11075.000000,26530.000000,63504.000000,99990.000000
geolocation_lat,1000163.0,-21.176153,5.715866,-36.605374,-23.603546,-22.919377,-19.979620,45.065933
geolocation_lng,1000163.0,-46.390541,4.269748,-101.466766,-48.573172,-46.637879,-43.767709,121.105394

======================================================================
ORDER_ITEMS
======================================================================

,count,mean,std,min,25%,50%,75%,max
order_item_id,112650.0,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00
price,112650.0,120.653739,183.633928,0.85,39.90,74.99,134.90,6735.00
freight_value,112650.0,19.990320,15.806405,0.00,13.08,16.26,21.15,409.68

======================================================================
PAYMENTS
======================================================================

,count,mean,std,min,25%,50%,75%,max
payment_sequential,103886.0,1.092679,0.706584,1.0,1.00,1.0,1.0000,29.00
payment_installments,103886.0,2.853349,2.687051,0.0,1.00,1.0,4.0000,24.00
payment_value,103886.0,154.100380,217.494064,0.0,56.79,100.0,171.8375,13664.08

======================================================================
REVIEWS
======================================================================

                count      mean       std  min  25%  50%  75%  max
review_score  99224.0  4.086421  1.347579  1.0  4.0  5.0  5.0  5.0

======================================================================
ORDERS
======================================================================

,count,unique,top,freq
order_id,99441,99441,66dea50a8b16d9b4dee7af250b4be1a5,1
customer_id,99441,99441,edb027a75a1449115f6b43211ae02a24,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:05:26,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 19:36:48,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

======================================================================
PRODUCTS
======================================================================

,count,mean,std,min,25%,50%,75%,max
product_name_lenght,32341.0,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

======================================================================
SELLERS
======================================================================

,count,mean,std,min,25%,50%,75%,max
seller_zip_code_prefix,3095.0,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0

======================================================================
TRANSLATION
======================================================================

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

Categorical Summary

In [16]:
for name, df in datasets.items():
    
    categorical_columns = df.select_dtypes(
        include="object"
    ).columns
    
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    
    for col in categorical_columns:
        print(f"\n{col}")
        print(df[col].value_counts().head(10))

======================================================================
CUSTOMERS
======================================================================

customer_id
customer_id
274fa6071e5e17fe303b9748641082c8    1
e5ed7280cd1a3ac2ba29fd6650d8867c    1
c6ece8a5137f3c9c3a3a12302a19a2ac    1
821a7275a08f32975caceff2e08ea262    1
5eef6cce1f34954c9e7004332388ccc7    1
be631308cb609ff74d0e0fb54815e18c    1
a1b5ca506b592bb72d4caadcbfe71385    1
30c96385d694acb8aa2dc0df1770120b    1
b7c889215de76857c7967c1011125d2d    1
c156d63bdfce1d456bd43cf1c4dadfca    1
Name: count, dtype: int64

customer_unique_id
customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
6469f99c1f9dfae7733b25662e7f1782     7
ca77025e7201e3b30c44b472ff346268     7
1b6c7548a2a1f9037c1fd3ddfed95f33     7
12f5d6e1cbf93dafd9dcc19095df0b3d     6
dc813062e0fc23409cd255f7f53c7074     6
47c1a3033b8b77b3ab6e109eb4d5fdf3     6
de34b16117594161a6a89c50b289d35a     6
63cfc61cee11cbe306bff5857d00bfe4     6
Name: count, dtype: int64

customer_city
customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
Name: count, dtype: int64

customer_state
customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
Name: count, dtype: int64

======================================================================
GEOLOCATION
======================================================================

geolocation_city
geolocation_city
sao paulo                135800
rio de janeiro            62151
belo horizonte            27805
são paulo                 24918
curitiba                  16593
porto alegre              13521
salvador                  11865
guarulhos                 11340
brasilia                  10470
sao bernardo do campo      8112
Name: count, dtype: int64

geolocation_state
geolocation_state
SP    404268
MG    126336
RJ    121169
RS     61851
PR     57859
SC     38328
BA     36045
GO     20139
ES     16748
PE     16432
Name: count, dtype: int64

======================================================================
ORDER_ITEMS
======================================================================

order_id
order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
9ef13efd6949e4573a18964dd1bbe7f5    15
428a2f660dc84138d969ccd69a0ab6d5    15
9bdc4d4c71aa1de4606060929dee888c    14
73c8ab38f07dc94389065f7eba4f297a    14
37ee401157a3a0b28c9c6d0ed8c3b24b    13
af822dacd6f5cff7376413c03a388bb7    12
3a213fcdfe7d98be74ea0dc05a8b31ae    12
Name: count, dtype: int64

product_id
product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
Name: count, dtype: int64

seller_id
seller_id
6560211a19b47992c3666cc44a7e94c0    2033
4a3ca9315b744ce9f8e9374361493884    1987
1f50f920176fa81dab994f9023523100    1931
cc419e0650a3c5ba77189a1882b7556a    1775
da8622b14eb17ae2831f4ac5b9dab84a    1551
955fee9216a65b617aa5c0531780ce60    1499
1025f0e2d44d7041d6cf58b6550e0bfa    1428
7c67e1448b00f6e969d365cea6b010ab    1364
ea8482cd71df3c1969d7b9473ff13abc    1203
7a67c85e85bb2ce8582c35f2203ad736    1171
Name: count, dtype: int64

shipping_limit_date
shipping_limit_date
2017-07-21 18:25:23    21
2018-03-01 02:50:48    21
2017-08-30 14:30:23    20
2017-12-21 02:30:41    15
2017-11-30 10:30:51    15
2017-02-03 21:44:49    15
2018-02-28 11:48:12    14
2018-06-13 17:30:35    13
2018-04-25 22:11:43    13
2018-04-19 02:30:52    13
Name: count, dtype: int64

======================================================================
PAYMENTS
======================================================================

order_id
order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
ee9ca989fc93ba09a6eddc250ce01742    19
21577126c19bf11a0b91592e5844ba78    15
4bfcba9e084f46c8e3cb49b0fa6e6159    15
4689b1816de42507a7d63a4617383c59    14
3c58bffb70dcf45f12bdf66a3c215905    14
Name: count, dtype: int64

payment_type
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

======================================================================
REVIEWS
======================================================================

review_id
review_id
08528f70f579f0c830189efc523d2182    3
c444278834184f72b1484dfe47de7f97    3
39b4603793c1c7f5f36d809b4a218664    3
44e9f871226d8a130de3fc39dfbdf0c5    3
1fb4ddc969e6bea80e38deec00393a6f    3
2d6ac45f859465b5c185274a1c929637    3
f4bb9d6dd4fb6dcc2298f0e7b17b8e1e    3
2172867fd5b1a55f98fe4608e1547b4b    3
32415bbf6e341d5d517080a796f79b5c    3
7b606b0d57b078384f0b58eac1d41d78    3
Name: count, dtype: int64

order_id
order_id
df56136b8031ecd28e200bb18e6ddb2e    3
c88b1d1b157a9999ce368f218a407141    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
029863af4b968de1e5d6a82782e662f5    2
29062384ce4975f78aeba6a496510386    2
bbf6a647ecc68aa5e79d2cd75ef44c68    2
7f13a20e25350f4a55fb2a7c9a2e8d88    2
aef2bc3845eb581cecce74b769d46c6a    2
0ed5043fe7d3f4f88353697330bbc020    2
Name: count, dtype: int64

review_comment_title
review_comment_title
Recomendo          423
recomendo          345
Bom                293
super recomendo    270
Excelente          248
Muito bom          247
Ótimo              240
Super recomendo    217
Ótimo              207
Otimo              174
Name: count, dtype: int64

review_comment_message
review_comment_message
Muito bom    230
Bom          189
muito bom    122
bom          107
Recomendo    100
Otimo         99
otimo         96
Ótimo         77
Ótimo         74
Ok            72
Name: count, dtype: int64

review_creation_date
review_creation_date
2017-12-19 00:00:00    463
2018-08-28 00:00:00    452
2017-12-20 00:00:00    440
2018-05-19 00:00:00    434
2018-05-15 00:00:00    425
2018-08-14 00:00:00    423
2018-03-29 00:00:00    421
2018-05-22 00:00:00    414
2018-05-04 00:00:00    412
2018-04-12 00:00:00    408
Name: count, dtype: int64

review_answer_timestamp
review_answer_timestamp
2017-06-15 23:21:05    4
2017-09-02 12:13:03    3
2018-02-26 15:53:18    3
2018-02-23 10:58:06    3
2018-03-21 01:02:05    3
2018-06-17 23:48:04    3
2017-09-05 12:12:51    3
2018-08-31 22:29:09    3
2017-02-14 13:58:48    3
2018-09-03 09:33:00    3
Name: count, dtype: int64

======================================================================
ORDERS
======================================================================

order_id
order_id
66dea50a8b16d9b4dee7af250b4be1a5    1
6ec4642f9993cc34f826cfb9068e5a2f    1
38e9133ce29f6bbe35aed9c3863dce01    1
dfc6eb45a2753ed9e6c6ef4987b44503    1
6f46d42016226f77893ed3978d6903d0    1
f9e3402be5a5ea63344347582ca9f45f    1
1b4a0e6b19d0034b531655b41ea89623    1
788541a19c0791de0504c5a9cb7e7bd5    1
e6cc57f923c4dab2222b8c9aa8742eea    1
c627fe35fce1a754bc5b812d0b8ff379    1
Name: count, dtype: int64

customer_id
customer_id
edb027a75a1449115f6b43211ae02a24    1
f00bb12620b7b232233cace1b229db18    1
ad312389a098ceff46ce92c4595c06d0    1
a046c690e0564ffde0ce611b5eee2c30    1
3803547f820b1e10b7ad9c7985f06753    1
6f2cf56878f7f82151b0ad02590192c0    1
ce5efd1b1d8a2fa290a871edd5c26cd6    1
a537aaf902d2f436eb7f44817154bb68    1
2f4a42f9bb4b9a8cd402fa549df5c7fd    1
42b0671b440d1f2527bddd8b723e0a0c    1
Name: count, dtype: int64

order_status
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

order_purchase_timestamp
order_purchase_timestamp
2018-08-02 12:05:26    3
2018-07-28 13:11:22    3
2018-02-19 15:37:47    3
2018-08-02 12:06:09    3
2018-03-31 15:08:21    3
2017-11-20 11:46:30    3
2018-04-11 10:48:14    3
2017-11-20 10:59:08    3
2018-08-02 12:06:07    3
2018-06-01 13:39:44    3
Name: count, dtype: int64

order_approved_at
order_approved_at
2018-02-27 04:31:10    9
2017-12-05 10:30:42    7
2018-02-06 05:31:52    7
2017-11-07 07:30:38    7
2017-11-07 07:30:29    7
2018-07-05 16:33:01    7
2018-01-10 10:32:03    7
2018-02-27 04:31:01    7
2018-07-27 04:05:17    6
2018-02-27 04:31:04    6
Name: count, dtype: int64

order_delivered_carrier_date
order_delivered_carrier_date
2018-05-09 15:48:00    47
2018-05-10 18:29:00    32
2018-05-07 12:31:00    21
2018-05-02 15:15:00    16
2018-07-24 16:07:00    16
2018-08-08 15:01:00    15
2018-05-16 13:44:00    15
2018-08-03 15:10:00    15
2018-07-17 14:16:00    15
2018-05-17 15:06:00    14
Name: count, dtype: int64

order_delivered_customer_date
order_delivered_customer_date
2018-05-08 19:36:48    3
2018-05-14 20:02:44    3
2018-05-08 23:38:46    3
2016-10-27 17:32:07    3
2018-07-24 21:36:42    3
2017-06-19 18:47:51    3
2017-12-02 00:26:45    3
2018-02-14 21:09:19    3
2017-05-13 09:37:37    2
2018-01-08 22:04:15    2
Name: count, dtype: int64

order_estimated_delivery_date
order_estimated_delivery_date
2017-12-20 00:00:00    522
2018-03-12 00:00:00    516
2018-05-29 00:00:00    513
2018-03-13 00:00:00    513
2018-02-14 00:00:00    507
2017-12-18 00:00:00    493
2018-03-06 00:00:00    492
2018-05-28 00:00:00    492
2018-02-06 00:00:00    491
2018-04-12 00:00:00    490
Name: count, dtype: int64

======================================================================
PRODUCTS
======================================================================

product_id
product_id
106392145fca363410d287a815be6de4    1
1e9e8ef04dbcff4541ed26657ea517e5    1
3aa071139cb16b67ca9e5dea641aaa2f    1
96bd76ec8810374ed1b65e291975717f    1
cef67bcfe19066a932b7673e239eb23d    1
9dc1a7de274444849c219cff195d0b71    1
41d3672d4792049fa1779bb35283ed13    1
1060d9ab6b911bfce1439c25afcd790b    1
6f79d50d852c044e3f7f0954d13aeacf    1
0bf1dea484fbb8cdfa09e2767ce30574    1
Name: count, dtype: int64

product_category_name
product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

======================================================================
SELLERS
======================================================================

seller_id
seller_id
9e25199f6ef7e7c347120ff175652c3b    1
3442f8959a84dea7ee197c632cb2df15    1
d1b65fc7debc3361ea86b5f14c68d2e2    1
ce3ad9de960102d0677a81f5d0bb7b2d    1
c0f3eea2e14555b6faeea3dd58c1b1c3    1
51a04a8a6bdcb23deccc82b0b80742cf    1
c240c4061717ac1806ae6ee72be3533b    1
63704069d9bd3a75c1cf59babe56004a    1
747e73c01a4593d4cf60dcf970fd2689    1
9e6967d3cf386d284251784b18ccb485    1
Name: count, dtype: int64

seller_city
seller_city
sao paulo         694
curitiba          127
rio de janeiro     96
belo horizonte     68
ribeirao preto     52
guarulhos          50
ibitinga           49
santo andre        45
campinas           41
maringa            40
Name: count, dtype: int64

seller_state
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
Name: count, dtype: int64

======================================================================
TRANSLATION
======================================================================

product_category_name
product_category_name
beleza_saude              1
informatica_acessorios    1
automotivo                1
cama_mesa_banho           1
moveis_decoracao          1
esporte_lazer             1
perfumaria                1
utilidades_domesticas     1
telefonia                 1
relogios_presentes        1
Name: count, dtype: int64

product_category_name_english
product_category_name_english
health_beauty            1
computers_accessories    1
auto                     1
bed_bath_table           1
furniture_decor          1
sports_leisure           1
perfumery                1
housewares               1
telephony                1
watches_gifts            1
Name: count, dtype: int64

Inspect Orders Dataset

In [17]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [18]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [19]:
orders.describe(include="all").T

,count,unique,top,freq
order_id,99441,99441,66dea50a8b16d9b4dee7af250b4be1a5,1
customer_id,99441,99441,edb027a75a1449115f6b43211ae02a24,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:05:26,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 19:36:48,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

Inspect Order Status

In [20]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [21]:
orders["order_status"].value_counts(normalize=True).mul(100).round(2)

order_status
delivered      97.02
shipped         1.11
canceled        0.63
unavailable     0.61
invoiced        0.32
processing      0.30
created         0.01
approved        0.00
Name: proportion, dtype: float64

Inspect Products

In [31]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [32]:

products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [33]:

products.describe().T

,count,mean,std,min,25%,50%,75%,max
product_name_lenght,32341.0,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

Inspect Order Items

In [30]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [29]:
order_items.describe().T

,count,mean,std,min,25%,50%,75%,max
order_item_id,112650.0,1.197834,0.705124,1.00,1.00,1.00,1.00,21.00
price,112650.0,120.653739,183.633928,0.85,39.90,74.99,134.90,6735.00
freight_value,112650.0,19.990320,15.806405,0.00,13.08,16.26,21.15,409.68

Inspect Customers

In [28]:
customers.head()

print("=" * 70)

customers["customer_state"].value_counts()

======================================================================

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [27]:
customers["customer_city"].value_counts().head(20)

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
niteroi                    849
santo andre                797
osasco                     746
santos                     713
goiania                    692
sao jose dos campos        691
fortaleza                  654
sorocaba                   633
recife                     613
florianopolis              570
Name: count, dtype: int64

Inspect Sellers

In [34]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [35]:

sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
MS       5
RN       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

Inspect Payments

In [36]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [37]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [38]:
payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

Inspect Reviews

In [39]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [40]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

Convert Date Columns
(start preparing the data for analytics)

In [41]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(
        orders[col],
        errors="coerce"
    )

print(orders[date_columns].dtypes)

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

Create Basic Delivery Metrics
(Now calculate delivery time.)

In [42]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_purchase_timestamp"]
).dt.total_seconds() / (60 * 60 * 24)

orders["delivery_days"].describe()

count    96476.000000
mean        12.558702
std          9.546530
min          0.533414
25%          6.766403
50%         10.217755
75%         15.720327
max        209.628611
Name: delivery_days, dtype: float64

Calculate Late Delivery

In [43]:
#Compare actual delivery with estimated delivery.

orders["is_late"] = (
    orders["order_delivered_customer_date"]
    > orders["order_estimated_delivery_date"]
)

orders["is_late"].value_counts()

is_late
False    91614
True      7827
Name: count, dtype: int64

In [45]:
#Percentage

late_percentage = orders["is_late"].mean() * 100

print(f"Late delivery percentage: {late_percentage:.2f}%")

Late delivery percentage: 7.87%

Basic Revenue Calculation

In [46]:
#Revenue comes from order_items

total_revenue = order_items["price"].sum()

print(f"Total Revenue: {total_revenue:,.2f}")

Total Revenue: 13,591,643.70

In [47]:
#Freight

total_freight = order_items["freight_value"].sum()

print(f"Total Freight: {total_freight:,.2f}")

Total Freight: 2,251,909.54

Number of Orders and Customers

In [48]:
total_orders = orders["order_id"].nunique()
total_customers = customers["customer_unique_id"].nunique()

print(f"Total Orders: {total_orders:,}")
print(f"Total Customers: {total_customers:,}")

Total Orders: 99,441
Total Customers: 96,096

Average Order Value

In [49]:
aov = total_revenue / total_orders

print(f"Average Order Value: {aov:,.2f}")

Average Order Value: 136.68

Create Initial KPI Summary

(Now combine everything we've learned.)

In [50]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Total Orders",
        "Total Customers",
        "Average Order Value",
        "Total Freight",
        "Average Delivery Days",
        "Late Delivery %"
    ],
    
    "Value": [
        total_revenue,
        total_orders,
        total_customers,
        aov,
        total_freight,
        orders["delivery_days"].mean(),
        late_percentage
    ]
})

kpi_summary

                     KPI         Value
0          Total Revenue  1.359164e+07
1           Total Orders  9.944100e+04
2        Total Customers  9.609600e+04
3    Average Order Value  1.366805e+02
4          Total Freight  2.251910e+06
5  Average Delivery Days  1.255870e+01
6        Late Delivery %  7.870999e+00

Create Data Quality Summary


This will eventually become part of our Data Quality Agent.

In [51]:
quality_summary = []

for name, df in datasets.items():
    
    total_cells = df.shape[0] * df.shape[1]
    missing_cells = df.isnull().sum().sum()
    duplicate_rows = df.duplicated().sum()
    
    quality_summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Cells": missing_cells,
        "Missing %": round(
            (missing_cells / total_cells) * 100, 2
        ),
        "Duplicate Rows": duplicate_rows
    })

quality_summary = pd.DataFrame(quality_summary)

quality_summary

       Dataset     Rows  Columns  Missing Cells  Missing %  Duplicate Rows
0    customers    99441        5              0       0.00               0
1  geolocation  1000163        5              0       0.00          261831
2  order_items   112650        7              0       0.00               0
3     payments   103886        5              0       0.00               0
4      reviews    99224        7         145903      21.01               0
5       orders    99441       10           7873       0.79               0
6     products    32951        9           2448       0.83               0
7      sellers     3095        4              0       0.00               0
8  translation       71        2              0       0.00               0

Save Initial Summary

In [53]:
import os

processed_path = "../data/processed"

os.makedirs(processed_path, exist_ok=True)

print("Processed folder ready:", os.path.exists(processed_path))

Processed folder ready: True

In [54]:
quality_summary.to_csv(
    "../data/processed/data_quality_summary.csv",
    index=False
)

kpi_summary.to_csv(
    "../data/processed/kpi_summary.csv",
    index=False
)

print("Summary files saved successfully!")

Summary files saved successfully!

In [55]:
print("=" * 60)
print("DATA UNDERSTANDING COMPLETED")
print("=" * 60)

print(f"Datasets loaded : {len(datasets)}")
print(f"Total orders    : {total_orders:,}")
print(f"Total customers : {total_customers:,}")
print(f"Total revenue   : {total_revenue:,.2f}")
print(f"Average order   : {aov:,.2f}")
print(f"Late delivery   : {late_percentage:.2f}%")

============================================================
DATA UNDERSTANDING COMPLETED
============================================================
Datasets loaded : 9
Total orders    : 99,441
Total customers : 96,096
Total revenue   : 13,591,643.70
Average order   : 136.68
Late delivery   : 7.87%

                         OLIST
                           │
                           ▼
                 ┌──────────────────┐
                 │ Data Understanding│
                 └─────────┬────────┘
                           │
          ┌────────────────┼────────────────┐
          ↓                ↓                ↓
      Structure       Data Quality       Business
      Analysis          Analysis         Metrics
          │                │                │
          ↓                ↓                ↓
      Tables          Missing Values      Revenue
      Columns          Duplicates         Orders
      Data Types       Data Types         Customers
                                           AOV
                                           Delivery